# Generated by Django 4.1.5 on 2023-01-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_likes_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_times',
            field=models.IntegerField(default=0),
        ),
    ]
