# Generated by Django 4.1.5 on 2023-01-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_saved_times_post_saved_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='favorites',
            new_name='saves',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_name',
        ),
    ]
