# Generated by Django 4.1.5 on 2023-01-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_user_post_author_rename_favorites_post_saves_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
